/*
  Warnings:

  - The values [CUTTING,STITCHING,WASHING,FINISHING,PACKAGING,DISPATCHED] on the enum `ORDER_ITEM_STATUS` will be removed. If these variants are still used in the database, this will fail.
  - You are about to drop the `Test` table. If the table is not empty, all the data it contains will be lost.

*/
-- CreateEnum
CREATE TYPE "ORDER_ITEM_CURRENT_STAGE" AS ENUM ('CUTTING', 'STITCHING', 'WASHING', 'FINISHING', 'PACKAGING', 'DISPATCHED');

-- CreateEnum
CREATE TYPE "CUTTING_STATUS" AS ENUM ('RAW_MATERIALS_ISSUED', 'COMPLETED');

-- CreateEnum
CREATE TYPE "STITCHING_STATUS" AS ENUM ('RAW_MATERIALS_ISSUED', 'COMPLETED');

-- CreateEnum
CREATE TYPE "WASHING_STATUS" AS ENUM ('PRODUCT_OUTSOURCED', 'COMPLETED');

-- CreateEnum
CREATE TYPE "FINISHING_STATUS" AS ENUM ('RAW_MATERIALS_ISSUED', 'COMPLETED');

-- CreateEnum
CREATE TYPE "QUALITY_CONTROL_STATUS" AS ENUM ('RAW_MATERIALS_ISSUED', 'COMPLETED');

-- CreateEnum
CREATE TYPE "PACKING_STATUS" AS ENUM ('RAW_MATERIALS_ISSUED', 'COMPLETED');

-- CreateEnum
CREATE TYPE "DISPATCHING_STATUS" AS ENUM ('RAW_MATERIALS_ISSUED', 'COMPLETED');

-- AlterEnum
BEGIN;
CREATE TYPE "ORDER_ITEM_STATUS_new" AS ENUM ('PENDING', 'COMPLETED');
ALTER TABLE "Order_Item" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Order_Item" ALTER COLUMN "status" TYPE "ORDER_ITEM_STATUS_new" USING ("status"::text::"ORDER_ITEM_STATUS_new");
ALTER TYPE "ORDER_ITEM_STATUS" RENAME TO "ORDER_ITEM_STATUS_old";
ALTER TYPE "ORDER_ITEM_STATUS_new" RENAME TO "ORDER_ITEM_STATUS";
DROP TYPE "ORDER_ITEM_STATUS_old";
ALTER TABLE "Order_Item" ALTER COLUMN "status" SET DEFAULT 'PENDING';
COMMIT;

-- AlterTable
ALTER TABLE "Item_Cutting" ADD COLUMN     "status" "CUTTING_STATUS" NOT NULL DEFAULT 'RAW_MATERIALS_ISSUED';

-- AlterTable
ALTER TABLE "Item_Dispatch" ADD COLUMN     "status" "DISPATCHING_STATUS" NOT NULL DEFAULT 'RAW_MATERIALS_ISSUED';

-- AlterTable
ALTER TABLE "Item_Finishing" ADD COLUMN     "status" "FINISHING_STATUS" NOT NULL DEFAULT 'RAW_MATERIALS_ISSUED';

-- AlterTable
ALTER TABLE "Item_Packaging" ADD COLUMN     "status" "PACKING_STATUS" NOT NULL DEFAULT 'RAW_MATERIALS_ISSUED';

-- AlterTable
ALTER TABLE "Item_Quality_Control" ADD COLUMN     "status" "QUALITY_CONTROL_STATUS" NOT NULL DEFAULT 'RAW_MATERIALS_ISSUED';

-- AlterTable
ALTER TABLE "Item_Stitching" ADD COLUMN     "status" "STITCHING_STATUS" NOT NULL DEFAULT 'RAW_MATERIALS_ISSUED';

-- AlterTable
ALTER TABLE "Item_Washing" ADD COLUMN     "status" "WASHING_STATUS" NOT NULL DEFAULT 'PRODUCT_OUTSOURCED';

-- AlterTable
ALTER TABLE "Order_Item" ADD COLUMN     "current_process" "ORDER_ITEM_CURRENT_STAGE" NOT NULL DEFAULT 'CUTTING',
ALTER COLUMN "status" SET DEFAULT 'PENDING';

-- DropTable
DROP TABLE "Test";
