/*
  Warnings:

  - The values [DISPATCHED] on the enum `ORDER_ITEM_CURRENT_STAGE` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "ORDER_ITEM_CURRENT_STAGE_new" AS ENUM ('CUTTING', 'STITCHING', 'WASHING', 'FINISHING', 'PACKAGING', 'DISPATCHING');
ALTER TABLE "Order_Item" ALTER COLUMN "current_process" DROP DEFAULT;
ALTER TABLE "Order_Item" ALTER COLUMN "current_process" TYPE "ORDER_ITEM_CURRENT_STAGE_new" USING ("current_process"::text::"ORDER_ITEM_CURRENT_STAGE_new");
ALTER TYPE "ORDER_ITEM_CURRENT_STAGE" RENAME TO "ORDER_ITEM_CURRENT_STAGE_old";
ALTER TYPE "ORDER_ITEM_CURRENT_STAGE_new" RENAME TO "ORDER_ITEM_CURRENT_STAGE";
DROP TYPE "ORDER_ITEM_CURRENT_STAGE_old";
ALTER TABLE "Order_Item" ALTER COLUMN "current_process" SET DEFAULT 'CUTTING';
COMMIT;
