name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
  packages: write
jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Github Container Registery
        run: echo "${{ secrets.GITHUB_TOKEN}}" | docker login ghcr.io -u ${{ github.actor}} --password-stdin

      - name: Extract and format repository name
        run: echo "REPO_NAME=$(echo '${{github.repository}} | tr '[:upper:] '[:lower:]')" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ env.REPO_NAME}}/${{ secrets.APP_NAME }}:lastest .

      - name: Push Docker image to Github Container Registery
        run: docker push ghcr.io/${{ env.REPO_NAME}}/${{ secrets.APP_NAME }}:latest

  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Login to Railway
        run: railway login --token ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy to Railway
        run: railway up --project ${{ secrets.RAILWAY_PROJECT_ID }}

  notify:
    name: Notify Whatsapp
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Send Whatsapp Notification
        run: |
          curl -X POST https://api.whatsapp.com/send \
          -H "Authorization: Bearer ${{ secrets.WHATSAPP_API_KEY}}" \
          -H "Content-Type: application/json" \
          -d '{
            "to": "${{ secrets.WHATSAPP_NUMBER}}",
            "message": "✅ Deployment Successful!\n\nRepository: `${{ github.repository }}`\nBranch: `${{ github.ref_name }}`\nWorkflow: `${{ github.workflow }}`\nCommit: `${{ github.sha }}`\nAuthor: `${{ github.actor }}`"
            }'
